dbt_transformation:
  outputs:
    dev:
      catalog: "{{env_var('DATABRICKS_CATALOG', 'abc')}}"
      host: 
      http_path: 
      schema: xyz
      threads: 1
      token: 
      type: databricks
  target: dev
