name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  airflow-dag-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Airflow DAGs
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/opt/airflow/project" \
            -e AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/project/airflow/dags \
            -e AIRFLOW__CORE__LOAD_EXAMPLES=false \
            -e AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db \
            -e PIP_ADDITIONAL_REQUIREMENTS="dbt-databricks" \
            apache/airflow:2.7.3 \
            bash -c "airflow db init && airflow dags list"
